version: '3.8'

services:
  # Servidor principal (frontend)
  web-server:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - checkers-api
    networks:
      - games-network

  # API do motor de damas
  checkers-api:
    build:
      context: ./jogos/Checkers
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENGINE_POOL_SIZE=4
      - MAX_DEPTH=20
      - MAX_TIME=10.0
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - games-network

  # Load balancer (opcional para alta disponibilidade)
  nginx-lb:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - checkers-api
    networks:
      - games-network

networks:
  games-network:
    driver: bridge

volumes:
  engine-cache:
    driver: local
